#!/usr/bin/python3
import MySQLdb
if __name__ = " __main__"
db=MySQLdb.connect(host=local.host, user="root", passwd=password, db=hbtn_0e_0_usa)
cur = db.cursor()
cur.execute("SELECT * FROM  states ORDER BY id ASC;")
states = cur.fetchall()
for state in state
print(state)
cusor.close()
db.close()
